
package Ejecución;

import Objetos.*;
import Estructuras.*;
import java.util.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class JDialog_MostrarUno extends javax.swing.JDialog {

    /**
     * Creates new form JDialog_MostrarUno
     */
    public JDialog_MostrarUno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoBordó = new javax.swing.JLabel();
        BuscarBoton = new javax.swing.JButton();
        BuscarOtroBoton = new javax.swing.JButton();
        VolverBoton = new javax.swing.JButton();
        doctxt = new javax.swing.JLabel();
        docf = new javax.swing.JTextField();
        jScrollPaneMostrar = new javax.swing.JScrollPane();
        jTextAreaDatos = new javax.swing.JTextArea();
        FondoBlanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoBordó.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo41.png"))); // NOI18N
        getContentPane().add(FondoBordó, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        BuscarBoton.setBackground(new java.awt.Color(102, 0, 0));
        BuscarBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BuscarBoton.setForeground(new java.awt.Color(255, 255, 255));
        BuscarBoton.setText("Buscar");
        BuscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBotonActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 210, 30));

        BuscarOtroBoton.setBackground(new java.awt.Color(51, 51, 51));
        BuscarOtroBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BuscarOtroBoton.setForeground(new java.awt.Color(255, 255, 255));
        BuscarOtroBoton.setText("Buscar otro");
        BuscarOtroBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarOtroBotonActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarOtroBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 210, 30));

        VolverBoton.setBackground(new java.awt.Color(51, 51, 51));
        VolverBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        VolverBoton.setForeground(new java.awt.Color(255, 255, 255));
        VolverBoton.setText("Volver");
        VolverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBotonActionPerformed(evt);
            }
        });
        getContentPane().add(VolverBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 210, 30));

        doctxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        doctxt.setForeground(new java.awt.Color(102, 0, 0));
        doctxt.setText("Ingrese el Nro. de Documento de la persona");
        getContentPane().add(doctxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 300, -1));
        getContentPane().add(docf, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 210, -1));

        jTextAreaDatos.setColumns(20);
        jTextAreaDatos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaDatos.setForeground(new java.awt.Color(51, 51, 51));
        jTextAreaDatos.setRows(5);
        jScrollPaneMostrar.setViewportView(jTextAreaDatos);

        getContentPane().add(jScrollPaneMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 430, 240));

        FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2222.png"))); // NOI18N
        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 510, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBotonActionPerformed
        // BOTÓN SALIR
        this.setVisible(false);
    }//GEN-LAST:event_VolverBotonActionPerformed

    private void BuscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBotonActionPerformed
        // TODO add your handling code here:
        int i;
        if (ControladoraLista.lista.exists(docf.getText())){
            i = ControladoraLista.lista.indexOf(docf.getText());
            jTextAreaDatos.setText((ControladoraLista.lista.get(i)).toString());
        }
        else 
            jTextAreaDatos.setText("La persona no está registrada");
    }//GEN-LAST:event_BuscarBotonActionPerformed

    private void BuscarOtroBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarOtroBotonActionPerformed
        // TODO add your handling code here:
        jTextAreaDatos.setText("");
        docf.setText("");
    }//GEN-LAST:event_BuscarOtroBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialog_MostrarUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialog_MostrarUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialog_MostrarUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialog_MostrarUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog_MostrarUno dialog = new JDialog_MostrarUno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarBoton;
    private javax.swing.JButton BuscarOtroBoton;
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel FondoBordó;
    private javax.swing.JButton VolverBoton;
    private javax.swing.JTextField docf;
    private javax.swing.JLabel doctxt;
    private javax.swing.JScrollPane jScrollPaneMostrar;
    private javax.swing.JTextArea jTextAreaDatos;
    // End of variables declaration//GEN-END:variables
}
