
package Ejecución;

import Objetos.*;
import Estructuras.*;
import java.util.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class JDialogConfirmacionRemoveAll extends javax.swing.JDialog {

    /**
     * Creates new form JDialogConfirmacionRemoveAll
     */
    public JDialogConfirmacionRemoveAll(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoBordó = new javax.swing.JLabel();
        segurotxt = new javax.swing.JLabel();
        doctxt = new javax.swing.JLabel();
        VolverBoton = new javax.swing.JButton();
        EliminarTodoBoton = new javax.swing.JButton();
        FondoBlanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoBordó.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo41.png"))); // NOI18N
        getContentPane().add(FondoBordó, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        segurotxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        segurotxt.setForeground(new java.awt.Color(102, 0, 0));
        segurotxt.setText("¿Seguro que quiere eliminar todo?");
        getContentPane().add(segurotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, -1));

        doctxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        doctxt.setForeground(new java.awt.Color(102, 0, 0));
        doctxt.setText("(Se borrarán todos los datos registrados)");
        getContentPane().add(doctxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 250, -1));

        VolverBoton.setBackground(new java.awt.Color(51, 51, 51));
        VolverBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        VolverBoton.setForeground(new java.awt.Color(255, 255, 255));
        VolverBoton.setText("Volver");
        VolverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBotonActionPerformed(evt);
            }
        });
        getContentPane().add(VolverBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 210, 50));

        EliminarTodoBoton.setBackground(new java.awt.Color(102, 0, 0));
        EliminarTodoBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EliminarTodoBoton.setForeground(new java.awt.Color(255, 255, 255));
        EliminarTodoBoton.setText("Eliminar todo");
        EliminarTodoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarTodoBotonActionPerformed(evt);
            }
        });
        getContentPane().add(EliminarTodoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 210, 50));

        FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2222.png"))); // NOI18N
        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 510, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBotonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_VolverBotonActionPerformed

    private void EliminarTodoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarTodoBotonActionPerformed
        // TODO add your handling code here:
        if (!ControladoraLista.lista.isEmpty()){
            while (!ControladoraLista.lista.isEmpty()){
                ControladoraLista.lista.removeFirst();
            }
            alert("Se eliminaron todos los datos","Eliminar");
        }
        else 
            alert("No hay datos registrados","Error");
    }//GEN-LAST:event_EliminarTodoBotonActionPerformed

    public static void alert(String mensaje, String titulo){
        JOptionPane.showMessageDialog(null, mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogConfirmacionRemoveAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogConfirmacionRemoveAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogConfirmacionRemoveAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogConfirmacionRemoveAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogConfirmacionRemoveAll dialog = new JDialogConfirmacionRemoveAll(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarTodoBoton;
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel FondoBordó;
    private javax.swing.JButton VolverBoton;
    private javax.swing.JLabel doctxt;
    private javax.swing.JLabel segurotxt;
    // End of variables declaration//GEN-END:variables
}
