/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejecución;

import Objetos.*;
import Estructuras.*;
import java.util.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;



public class JFrameInfo extends javax.swing.JFrame {

    /**
     * Creates new form JFrameInfo
     */
    public JFrameInfo() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoBordó = new javax.swing.JLabel();
        BuscarBoton = new javax.swing.JButton();
        cardinalidadBoton = new javax.swing.JButton();
        isemptyBoton = new javax.swing.JButton();
        VolverBoton = new javax.swing.JButton();
        FondoBlanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoBordó.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo41.png"))); // NOI18N
        getContentPane().add(FondoBordó, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        BuscarBoton.setBackground(new java.awt.Color(102, 0, 0));
        BuscarBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BuscarBoton.setForeground(new java.awt.Color(255, 255, 255));
        BuscarBoton.setText("Buscar persona en la lista");
        BuscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBotonActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 210, 50));

        cardinalidadBoton.setBackground(new java.awt.Color(102, 0, 0));
        cardinalidadBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cardinalidadBoton.setForeground(new java.awt.Color(255, 255, 255));
        cardinalidadBoton.setText("Total de personas registradas");
        cardinalidadBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardinalidadBotonActionPerformed(evt);
            }
        });
        getContentPane().add(cardinalidadBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 210, 50));

        isemptyBoton.setBackground(new java.awt.Color(102, 0, 0));
        isemptyBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        isemptyBoton.setForeground(new java.awt.Color(255, 255, 255));
        isemptyBoton.setText("Ver si la lista está vacía");
        isemptyBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isemptyBotonActionPerformed(evt);
            }
        });
        getContentPane().add(isemptyBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 210, 50));

        VolverBoton.setBackground(new java.awt.Color(51, 51, 51));
        VolverBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        VolverBoton.setForeground(new java.awt.Color(255, 255, 255));
        VolverBoton.setText("Volver");
        VolverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBotonActionPerformed(evt);
            }
        });
        getContentPane().add(VolverBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 210, 50));

        FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2222.png"))); // NOI18N
        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 510, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardinalidadBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardinalidadBotonActionPerformed
        // TODO add your handling code here:
        alert(("Hay "+ControladoraLista.lista.size()+" Persona/s registradas.") , "Info lista");
    }//GEN-LAST:event_cardinalidadBotonActionPerformed

    private void isemptyBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isemptyBotonActionPerformed
        // TODO add your handling code here:
        if (ControladoraLista.lista.isEmpty())
            alert("Lista vacía","Info lista");
        else 
            alert ("La lista no está vacía","Info lista");
    }//GEN-LAST:event_isemptyBotonActionPerformed

    private void VolverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBotonActionPerformed
        // BOTÓN SALIR
        this.setVisible(false);
    }//GEN-LAST:event_VolverBotonActionPerformed

    private void BuscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBotonActionPerformed
        // TODO add your handling code here:
        new JFrameBuscar().setVisible(true);
    }//GEN-LAST:event_BuscarBotonActionPerformed

    public static void alert(String mensaje, String titulo){
        JOptionPane.showMessageDialog(null, mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarBoton;
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel FondoBordó;
    private javax.swing.JButton VolverBoton;
    private javax.swing.JButton cardinalidadBoton;
    private javax.swing.JButton isemptyBoton;
    // End of variables declaration//GEN-END:variables
}
