
package Ejecución;

import javax.swing.ImageIcon;


public class JFrameEliminar extends javax.swing.JFrame {

    /**
     * Creates new form JFrameEliminar
     */
    public JFrameEliminar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoBordó = new javax.swing.JLabel();
        EliminarUnoBoton = new javax.swing.JButton();
        EliminarTodosBoton = new javax.swing.JButton();
        VolverBoton = new javax.swing.JButton();
        FondoBlanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoBordó.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo41.png"))); // NOI18N
        getContentPane().add(FondoBordó, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        EliminarUnoBoton.setBackground(new java.awt.Color(102, 0, 0));
        EliminarUnoBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EliminarUnoBoton.setForeground(new java.awt.Color(255, 255, 255));
        EliminarUnoBoton.setText("Eliminar una persona");
        EliminarUnoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUnoBotonActionPerformed(evt);
            }
        });
        getContentPane().add(EliminarUnoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 210, 50));

        EliminarTodosBoton.setBackground(new java.awt.Color(102, 0, 0));
        EliminarTodosBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EliminarTodosBoton.setForeground(new java.awt.Color(255, 255, 255));
        EliminarTodosBoton.setText("Eliminar a todos");
        EliminarTodosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarTodosBotonActionPerformed(evt);
            }
        });
        getContentPane().add(EliminarTodosBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 210, 50));

        VolverBoton.setBackground(new java.awt.Color(51, 51, 51));
        VolverBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        VolverBoton.setForeground(new java.awt.Color(255, 255, 255));
        VolverBoton.setText("Volver");
        VolverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBotonActionPerformed(evt);
            }
        });
        getContentPane().add(VolverBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 210, 50));

        FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2222.png"))); // NOI18N
        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 510, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarUnoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUnoBotonActionPerformed
        // TODO add your handling code here:
        new JDialog_BuscarparaEliminar(this,true).setVisible(true);
    }//GEN-LAST:event_EliminarUnoBotonActionPerformed

    private void EliminarTodosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarTodosBotonActionPerformed
        // TODO add your handling code here:
        new JDialogConfirmacionRemoveAll(this,true).setVisible(true);
    }//GEN-LAST:event_EliminarTodosBotonActionPerformed

    private void VolverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBotonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_VolverBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarTodosBoton;
    private javax.swing.JButton EliminarUnoBoton;
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel FondoBordó;
    private javax.swing.JButton VolverBoton;
    // End of variables declaration//GEN-END:variables
}
