package Ejecución;

import Objetos.*;
import Estructuras.*;
import java.util.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class JFrameBuscarParaModificar extends javax.swing.JFrame {

    /**
     * Creates new form JFrameBuscarParaModificar
     */
    public JFrameBuscarParaModificar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoBordó = new javax.swing.JLabel();
        VolverBoton = new javax.swing.JButton();
        SiguienteBoton = new javax.swing.JButton();
        docf = new javax.swing.JTextField();
        doctxt = new javax.swing.JLabel();
        FondoBlanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoBordó.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo41.png"))); // NOI18N
        getContentPane().add(FondoBordó, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        VolverBoton.setBackground(new java.awt.Color(51, 51, 51));
        VolverBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        VolverBoton.setForeground(new java.awt.Color(255, 255, 255));
        VolverBoton.setText("Volver");
        VolverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBotonActionPerformed(evt);
            }
        });
        getContentPane().add(VolverBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 210, 50));

        SiguienteBoton.setBackground(new java.awt.Color(102, 0, 0));
        SiguienteBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SiguienteBoton.setForeground(new java.awt.Color(255, 255, 255));
        SiguienteBoton.setText("Siguiente");
        SiguienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteBotonActionPerformed(evt);
            }
        });
        getContentPane().add(SiguienteBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 210, 50));
        getContentPane().add(docf, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 210, -1));

        doctxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        doctxt.setForeground(new java.awt.Color(102, 0, 0));
        doctxt.setText("Nro. de Documento de la persona a modificar:");
        getContentPane().add(doctxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 320, -1));

        FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2222.png"))); // NOI18N
        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 510, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBotonActionPerformed
        // BOTÓN SALIR
        this.setVisible(false);
    }//GEN-LAST:event_VolverBotonActionPerformed

    private static int indMod;

    private void SiguienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteBotonActionPerformed
        // TODO add your handling code here:
        if (ControladoraLista.lista.exists(docf.getText())) {
            setIndMod(ControladoraLista.lista.indexOf(docf.getText()));
            String clase = (ControladoraLista.lista.get(getIndMod())).getClass().toString();
            if (clase.equals("class Objetos.Alumno")) {
                docf.setText("");
                new JFrameModificarAlumno().setVisible(true);
            } else if (clase.equals("class Objetos.AlumnoPostGrado")) {
                docf.setText("");
                new JFrameModificarAlumnoPG().setVisible(true);
            } else if (clase.equals("class Objetos.Docente")) {
                docf.setText("");
                new JFrameModificarDocente().setVisible(true);
            }
        } else {
            alert("La persona no está registrada", "Error");
            docf.setText("");
        }
    }//GEN-LAST:event_SiguienteBotonActionPerformed

    public void setIndMod(int i) {
        this.indMod = i;
    }

    public int getIndMod() {
        return this.indMod;
    }

    public static void alert(String mensaje, String titulo) {
        JOptionPane.showMessageDialog(null, mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameBuscarParaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameBuscarParaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameBuscarParaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameBuscarParaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameBuscarParaModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel FondoBordó;
    private javax.swing.JButton SiguienteBoton;
    private javax.swing.JButton VolverBoton;
    private javax.swing.JTextField docf;
    private javax.swing.JLabel doctxt;
    // End of variables declaration//GEN-END:variables
}
