package Ejecución;

import Objetos.*;
import Estructuras.*;
import java.util.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class JFrameModificarDocente extends javax.swing.JFrame {

    /**
     * Creates new form JFrameModificarDocente
     */
    public JFrameModificarDocente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage());
        
        int i = new JFrameBuscarParaModificar().getIndMod();

        nomf.setText((ControladoraLista.lista.get(i)).getNbre());
        docf.setText((ControladoraLista.lista.get(i)).getDoc());
        dirf.setText((ControladoraLista.lista.get(i)).getDir());
        int fecNac[] = new int[3];
        fecNac = ((ControladoraLista.lista.get(i)).getfNac());
        diaNacf.setText(("" + fecNac[0]));
        mesNacf.setText("" + fecNac[1]);
        añoNacf.setText("" + fecNac[2]);
        facf.setText(((Docente) ControladoraLista.lista.get(i)).getFac());
        carrf.setText(((Docente) ControladoraLista.lista.get(i)).getCar());
        int fecIng[] = new int[3];
        fecIng = ((((Docente) ControladoraLista.lista.get(i)).getfIng()));
        diaIngref.setText("" + fecIng[0]);
        mesIngref.setText("" + fecIng[1]);
        añoingref.setText("" + fecIng[2]);
        cargof.setText(((Docente) ControladoraLista.lista.get(i)).getCargo());

        int longi = (((Docente) ControladoraLista.lista.get(i)).getMat().size());
        switch (longi) {
            case 0:
                mat1f.setText("");
                mat2f.setText("");
                mat3f.setText("");
                mat4f.setText("");
                break;

            case 1:
                mat1f.setText((((Docente) ControladoraLista.lista.get(i)).getMat()).get(0));
                mat2f.setText("");
                mat3f.setText("");
                mat4f.setText("");
                break;

            case 2:
                mat1f.setText((((Docente) ControladoraLista.lista.get(i)).getMat()).get(0));
                mat2f.setText((((Docente) ControladoraLista.lista.get(i)).getMat()).get(1));
                mat3f.setText("");
                mat4f.setText("");
                break;

            case 3:
                mat1f.setText((((Docente) ControladoraLista.lista.get(i)).getMat()).get(0));
                mat2f.setText((((Docente) ControladoraLista.lista.get(i)).getMat()).get(1));
                mat3f.setText((((Docente) ControladoraLista.lista.get(i)).getMat()).get(2));
                mat4f.setText("");
                break;

            case 4:
                mat1f.setText((((Docente) ControladoraLista.lista.get(i)).getMat()).get(0));
                mat2f.setText((((Docente) ControladoraLista.lista.get(i)).getMat()).get(1));
                mat3f.setText((((Docente) ControladoraLista.lista.get(i)).getMat()).get(2));
                mat4f.setText((((Docente) ControladoraLista.lista.get(i)).getMat()).get(3));
                break;
        }//end switch
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomf = new javax.swing.JTextField();
        docf = new javax.swing.JTextField();
        dirf = new javax.swing.JTextField();
        añoNacf = new javax.swing.JTextField();
        mesNacf = new javax.swing.JTextField();
        diaNacf = new javax.swing.JTextField();
        facf = new javax.swing.JTextField();
        carrf = new javax.swing.JTextField();
        añoingref = new javax.swing.JTextField();
        mesIngref = new javax.swing.JTextField();
        diaIngref = new javax.swing.JTextField();
        cargof = new javax.swing.JTextField();
        mat1f = new javax.swing.JTextField();
        mat2f = new javax.swing.JTextField();
        mat3f = new javax.swing.JTextField();
        mat4f = new javax.swing.JTextField();
        fecnactxt = new javax.swing.JLabel();
        carrtxt = new javax.swing.JLabel();
        nomtxt = new javax.swing.JLabel();
        factxt = new javax.swing.JLabel();
        dirtxt = new javax.swing.JLabel();
        fecingretxt = new javax.swing.JLabel();
        cargotxt = new javax.swing.JLabel();
        doctxt = new javax.swing.JLabel();
        materiastxt = new javax.swing.JLabel();
        modificarBoton = new javax.swing.JButton();
        volverBoton = new javax.swing.JButton();
        FondoBordó = new javax.swing.JLabel();
        FondoBlanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(nomf, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 180, -1));
        getContentPane().add(docf, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 180, -1));
        getContentPane().add(dirf, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 180, -1));
        getContentPane().add(añoNacf, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 40, -1));
        getContentPane().add(mesNacf, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 20, -1));
        getContentPane().add(diaNacf, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 20, -1));
        getContentPane().add(facf, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 180, -1));
        getContentPane().add(carrf, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 180, -1));
        getContentPane().add(añoingref, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 40, -1));
        getContentPane().add(mesIngref, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, 20, -1));
        getContentPane().add(diaIngref, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 20, -1));
        getContentPane().add(cargof, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 180, -1));
        getContentPane().add(mat1f, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 30, -1));
        getContentPane().add(mat2f, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, 30, -1));
        getContentPane().add(mat3f, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 350, 30, -1));
        getContentPane().add(mat4f, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, 30, -1));

        fecnactxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fecnactxt.setForeground(new java.awt.Color(102, 0, 0));
        fecnactxt.setText("Fecha de nacimiento");
        getContentPane().add(fecnactxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        carrtxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carrtxt.setForeground(new java.awt.Color(102, 0, 0));
        carrtxt.setText("Carrera");
        getContentPane().add(carrtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, -1, -1));

        nomtxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomtxt.setForeground(new java.awt.Color(102, 0, 0));
        nomtxt.setText("Nombre y Apellido");
        getContentPane().add(nomtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        factxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        factxt.setForeground(new java.awt.Color(102, 0, 0));
        factxt.setText("Facultad");
        getContentPane().add(factxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, -1, -1));

        dirtxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dirtxt.setForeground(new java.awt.Color(102, 0, 0));
        dirtxt.setText("Dirección");
        getContentPane().add(dirtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, -1, -1));

        fecingretxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fecingretxt.setForeground(new java.awt.Color(102, 0, 0));
        fecingretxt.setText("Fecha de ingreso");
        getContentPane().add(fecingretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, -1, -1));

        cargotxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cargotxt.setForeground(new java.awt.Color(102, 0, 0));
        cargotxt.setText("Cargo");
        getContentPane().add(cargotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, -1));

        doctxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        doctxt.setForeground(new java.awt.Color(102, 0, 0));
        doctxt.setText("Nro. de Documento");
        getContentPane().add(doctxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, -1, -1));

        materiastxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        materiastxt.setForeground(new java.awt.Color(102, 0, 0));
        materiastxt.setText("Materias que dicta");
        getContentPane().add(materiastxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, -1, -1));

        modificarBoton.setBackground(new java.awt.Color(102, 0, 0));
        modificarBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        modificarBoton.setForeground(new java.awt.Color(255, 255, 255));
        modificarBoton.setText("Modificar");
        modificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBotonActionPerformed(evt);
            }
        });
        getContentPane().add(modificarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 180, 30));

        volverBoton.setBackground(new java.awt.Color(51, 51, 51));
        volverBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        volverBoton.setForeground(new java.awt.Color(255, 255, 255));
        volverBoton.setText("Volver");
        volverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBotonActionPerformed(evt);
            }
        });
        getContentPane().add(volverBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 180, 30));

        FondoBordó.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo41.png"))); // NOI18N
        getContentPane().add(FondoBordó, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2222.png"))); // NOI18N
        FondoBlanco.setText("Carrera de Post Grado");
        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 510, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBotonActionPerformed
        // TODO add your handling code here:
        int [] fNac = new int[3];
        int [] fIngre = new int[3];
        int aux = 0;

        int i = new JFrameBuscarParaModificar().getIndMod();

        //Campos de fecha vacíos
        if      (  !diaNacf.getText().equals("")
                && !mesNacf.getText().equals("") 
                && !añoNacf.getText().equals("")
                && !diaIngref.getText().equals("") 
                && !mesIngref.getText().equals("") 
                && !añoingref.getText().equals("")) {
             
            //Fechas inválidas 
            //inicio if
            if (Integer.parseInt(diaNacf.getText()) >= 1 && Integer.parseInt(diaNacf.getText()) <= 31)
                fNac[0] = Integer.parseInt(diaNacf.getText());
            else aux = 16;
            
            if (Integer.parseInt(mesNacf.getText()) >= 1 && Integer.parseInt(mesNacf.getText()) <= 12)
                fNac[1] = Integer.parseInt(mesNacf.getText());
            else aux = 16;
            
            if (Integer.parseInt(añoNacf.getText()) >= 1915 && Integer.parseInt(añoNacf.getText()) <= 2021)
                fNac[2] = Integer.parseInt(añoNacf.getText());
            else aux = 16;

            //
            
            if (Integer.parseInt(diaIngref.getText()) >= 1 && Integer.parseInt(diaIngref.getText()) <= 31)
                fIngre[0] = Integer.parseInt(diaIngref.getText());
            else aux = 17;
            
            if (Integer.parseInt(mesIngref.getText()) >= 1 && Integer.parseInt(mesIngref.getText()) <= 12)
                fIngre[1] = Integer.parseInt(mesIngref.getText());
            else aux = 17;
            
            if (Integer.parseInt(añoingref.getText()) >= 1915 && Integer.parseInt(añoingref.getText()) <= 2021)
                fIngre[2] = Integer.parseInt(añoingref.getText());
            else aux = 17;
         } //end if
         else aux = 18;
        
        //16 -> fecha de nacimiento inválida
        //17 -> fecha de ingreso inválida
        //18 -> faltan campos

        //Campos vacíos
        if      (  aux != 18 && aux != 17 && aux != 16
                && !nomf.getText().equals("") 
                && !docf.getText().equals("") 
                && !dirf.getText().equals("")
                && !facf.getText().equals("") 
                && !carrf.getText().equals("")
                && !diaNacf.getText().equals("") 
                && !mesNacf.getText().equals("")
                && !añoNacf.getText().equals("") 
                && !diaIngref.getText().equals("") 
                && !mesIngref.getText().equals("")
                && !añoingref.getText().equals("")
                && !cargof.getText().equals("")){ 
            
            //inicio if
            Persona d = new Docente();
            d.setNbre(nomf.getText());
            d.setDoc(docf.getText());
            d.setDir(dirf.getText());
            d.setfNac(fNac);
            ((Docente)d).setFac(facf.getText());
            ((Docente)d).setCar(carrf.getText());
            ((Docente)d).setfIng(fIngre);
            ((Docente)d).setCargo(cargof.getText());

            int longi = ((Docente) ControladoraLista.lista.get(i)).getMat().size(); 
            
            for (int j = 0 ; j<longi ; j++){ 
                ((Docente) ControladoraLista.lista.get(i)).delMat(j);
            }

            if (!(mat1f.getText()).equals("")) {
                ((Docente) d).addMatFirst(mat1f.getText());
            }
            if (!(mat2f.getText()).equals("")) {
                ((Docente) d).addMatFirst(mat2f.getText());
            }
            if (!(mat3f.getText()).equals("")) {
                ((Docente) d).addMatFirst(mat3f.getText());
            }
            if (!(mat4f.getText()).equals("")) {
                ((Docente) d).addMatFirst(mat4f.getText());
            }

            ControladoraLista.lista.modify(d, i);

            alert("Docente modificado con éxito","Operación realizada");
            this.setVisible(false);
        } //end if
        else if(aux == 18) 
            alert("Debe ingresar todos los campos obligatorios","Error");
            else if(aux == 17)
                alert("Fecha de ingreso inválida","Error");
                else if(aux == 16)
                    alert("Fecha de nacimiento inválida","Error");
                    else alert("Debe ingresar todos los campos obligatorios","Error");
    }

    public static void alert(String mensaje, String titulo) {
        JOptionPane.showMessageDialog(null, mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_modificarBotonActionPerformed

    private void volverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBotonActionPerformed
        // BOTÓN SALIR
        this.setVisible(false);
    }//GEN-LAST:event_volverBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameModificarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameModificarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameModificarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameModificarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameModificarDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel FondoBordó;
    private javax.swing.JTextField añoNacf;
    private javax.swing.JTextField añoingref;
    private javax.swing.JTextField cargof;
    private javax.swing.JLabel cargotxt;
    private javax.swing.JTextField carrf;
    private javax.swing.JLabel carrtxt;
    private javax.swing.JTextField diaIngref;
    private javax.swing.JTextField diaNacf;
    private javax.swing.JTextField dirf;
    private javax.swing.JLabel dirtxt;
    private javax.swing.JTextField docf;
    private javax.swing.JLabel doctxt;
    private javax.swing.JTextField facf;
    private javax.swing.JLabel factxt;
    private javax.swing.JLabel fecingretxt;
    private javax.swing.JLabel fecnactxt;
    private javax.swing.JTextField mat1f;
    private javax.swing.JTextField mat2f;
    private javax.swing.JTextField mat3f;
    private javax.swing.JTextField mat4f;
    private javax.swing.JLabel materiastxt;
    private javax.swing.JTextField mesIngref;
    private javax.swing.JTextField mesNacf;
    private javax.swing.JButton modificarBoton;
    private javax.swing.JTextField nomf;
    private javax.swing.JLabel nomtxt;
    private javax.swing.JButton volverBoton;
    // End of variables declaration//GEN-END:variables
}
